version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:11

    working_directory: /tmp/

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: npm test

      - run:
          shell: /bin/bash
          command: |
            mkdir -p /tmp/test-results
            echo "done"
          when: always

      - store_test_results:
          path: /tmp/test-results

      - store_artifacts:
          path: /tmp/test-results
          destination: test_results
